name: TestPlugin
version: '1.0'
main: nl.inferno.testPlugin.TestPlugin
api-version: '1.20'
commands:
  hidemessage:
    description: Hide a specific broadcast message
    usage: /<command> <messageIndex>